'use strict';
(() => {
const C=window.ConstellationCore,E=window.ConstellationExport;
const KEY='imagination-constellation-v1:'+location.pathname;
const fresh=()=>({version:1,step:0,maxStep:0,observed:false,drawing:C.blank(),meta:{name:'',appearance:'',story:'',author:''},completed:false});
let state=fresh(),storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw?.version===1){state.drawing=C.normalize(raw.drawing);state.step=Number.isInteger(raw.step)?C.clamp(raw.step,0,6):0;state.maxStep=Math.max(state.step,Number.isInteger(raw.maxStep)?C.clamp(raw.maxStep,0,6):0);state.observed=!!raw.observed;state.completed=!!raw.completed;for(const [k,max] of Object.entries({name:24,appearance:80,story:240,author:16}))state.meta[k]=typeof raw.meta?.[k]==='string'?raw.meta[k].slice(0,max):'';if(state.step>=4&&C.largestGroup(state.drawing)<4)state.step=2;if(state.step===6&&(!state.meta.name.trim()||!state.meta.appearance.trim()||!state.meta.author.trim()))state.step=5;}}catch{storageOK=false}
const ui={tool:'add',selected:null,line:null,anchor:null,showDemo:false,freshFinish:false,hint:-1};
let undo=[],redo=[],gesture=null,pendingStroke=null,toastTimer=0;
const $=q=>document.querySelector(q);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,cls='secondary',attrs='')=>`<button data-action="${action}" class="${cls}" ${attrs}>${label}</button>`;
const steps=['별자리 떠올리기','별 배치하기','별 연결하기','모양 상상하기','이름과 이야기','작품 완성'];
const hints=['어떤 동물처럼 보이나요?','어떤 물건처럼 보이나요?','어떤 사람의 모습처럼 보이나요?','움직이는 모습으로 생각하면 무엇이 떠오르나요?','방향을 바꾸어 보면 무엇처럼 보이나요?','거꾸로 바라보면 또 어떤 모습이 보이나요?'];
const fieldStars=C.backgroundStars();
function notify(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch{storageOK=false}$('#save-status').textContent=storageOK?'이 기기에 작품 저장됨':'저장이 제한돼요 · 완료 후 PNG로 보관해요';$('#save-status').classList.toggle('warning',!storageOK)}
function commit(before){if(JSON.stringify(before)===JSON.stringify(state.drawing))return;undo.push(before);if(undo.length>50)undo.shift();redo=[];state.completed=false;save()}
function changeDrawing(fn){const before=C.copy(state.drawing);fn();commit(before);paintBoard();updateEditor()}
function undoAction(){if(!undo.length)return;redo.push(C.copy(state.drawing));state.drawing=undo.pop();ui.selected=ui.line=ui.anchor=null;state.completed=false;save();paintBoard();updateEditor();notify('이전 상태로 되돌렸어요.')}
function redoAction(){if(!redo.length)return;undo.push(C.copy(state.drawing));state.drawing=redo.pop();ui.selected=ui.line=ui.anchor=null;state.completed=false;save();paintBoard();updateEditor();notify('다시 실행했어요.')}
function go(step){if(step===3&&state.drawing.stars.length<2){notify('먼저 별을 2개 이상 만들어 주세요.');return}if(step>=4&&C.largestGroup(state.drawing)<4){notify('별 4개 이상이 하나로 이어지도록 연결해 주세요.');return}if(step===5&&!state.meta.appearance.trim()){notify('별을 이어 보니 어떤 모습이 떠올랐는지 적어 주세요.');$('[data-meta="appearance"]')?.focus();return}if(step===6){finish();return}state.step=step;state.maxStep=Math.max(state.maxStep,step);ui.tool=step===3?'connect':'add';ui.anchor=null;ui.selected=ui.line=null;save();render(true)}
function heading(k,title,subtitle){return `<div class="heading"><div class="eyebrow">STEP ${String(k).padStart(2,'0')} · 밤하늘 상상 연구소</div><h1>${title}</h1><p>${subtitle}</p></div>`}
function nav(next,label,note,enabled=true,back='back'){return `<div class="footer-nav">${button(back,'← 이전','quiet')}<p class="hint">${note}</p>${button(next,label+' →','primary',enabled?'':'disabled')}</div>`}
function background(id){return `<defs><linearGradient id="${id}-sky" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#101e39"/><stop offset="1" stop-color="#071226"/></linearGradient><radialGradient id="${id}-haze"><stop stop-color="#7c94b8" stop-opacity=".11"/><stop offset="1" stop-color="#7c94b8" stop-opacity="0"/></radialGradient><radialGradient id="${id}-star"><stop stop-color="#e3edff" stop-opacity=".43"/><stop offset="1" stop-color="#d5e4ff" stop-opacity="0"/></radialGradient>${C.STAR_COLORS.map(c=>`<radialGradient id="${id}-star-${c.id}"><stop stop-color="${c.hex}" stop-opacity=".43"/><stop offset="1" stop-color="${c.hex}" stop-opacity="0"/></radialGradient>`).join('')}</defs><g class="background" aria-hidden="true"><rect width="1200" height="700" fill="url(#${id}-sky)"/><ellipse cx="650" cy="345" rx="800" ry="160" transform="rotate(-24 650 345)" fill="url(#${id}-haze)"/>${fieldStars.map(s=>`<circle cx="${s.x*1200}" cy="${s.y*700}" r="${s.r}" fill="#dbe7ff" opacity="${s.opacity}"/>`).join('')}</g>`}
function starGraphic(s,id){const r=[3.5,5,7][s.size],a=[.65,.85,1][s.brightness],color=C.starColor(s);return `<circle r="${r*4}" fill="url(#${id}-star-${color.id})" opacity="${a}"/><circle class="star-core" r="${r}" fill="${color.hex}" opacity="${a}"/><circle r="${r*.35}" fill="#fff" opacity="${a}"/>`}
function svgContent(d,id,editable=false){const lookup=new Map(d.stars.map(s=>[s.id,s]));const radius=touchRadius();return background(id)+`<g aria-hidden="true">${d.strokes.map(st=>`<g data-stroke="${st.id}"><polyline class="sketch-hit" points="${st.points.map(p=>`${p.x*1200},${p.y*700}`).join(' ')}"/><polyline class="sketch-visible" points="${st.points.map(p=>`${p.x*1200},${p.y*700}`).join(' ')}"/></g>`).join('')}${pendingStroke?`<polyline class="sketch-visible" points="${pendingStroke.points.map(p=>`${p.x*1200},${p.y*700}`).join(' ')}"/>`:''}</g><g>${d.lines.map(l=>{const a=lookup.get(l.a),b=lookup.get(l.b);if(!a||!b)return '';return `<g data-line="${l.id}" ${editable?`role="button" tabindex="0" aria-label="별 ${lookupIndex(l.a)}과 별 ${lookupIndex(l.b)}의 연결선"`:''}><line class="edge-hit" x1="${a.x*1200}" y1="${a.y*700}" x2="${b.x*1200}" y2="${b.y*700}" stroke-width="${radius*1.7}"/><line class="edge-visible ${editable&&ui.line===l.id?'edge-selected':''}" x1="${a.x*1200}" y1="${a.y*700}" x2="${b.x*1200}" y2="${b.y*700}"/></g>`}).join('')}</g><g>${d.stars.map((s,i)=>`<g transform="translate(${s.x*1200} ${s.y*700})" data-star="${s.id}" ${editable?`tabindex="0" role="button" aria-label="별 ${i+1}, ${C.starColor(s).label}, ${['작은','중간','큰'][s.size]} 별"`:''}><circle class="star-hit" r="${radius}"/>${editable?`<circle class="focus-circle" r="${radius*.7}"/>`:''}${starGraphic(s,id)}${editable&&(ui.selected===s.id||ui.anchor===s.id)?`<circle class="selection-ring" r="${Math.max(16,radius*.6)}"/>`:''}</g>`).join('')}</g>`}
function lookupIndex(id){return state.drawing.stars.findIndex(s=>s.id===id)+1}
function board(editable=true,cls=''){return `<div class="canvas-shell ${cls}"><svg id="sky-board" class="board" viewBox="0 0 1200 700" preserveAspectRatio="xMidYMid meet" ${editable?'role="group" aria-label="별자리 제작 공간. 빈 곳을 누르면 별을 추가해요."':'role="img" aria-label="내가 만든 별과 연결선"'}></svg>${editable?'<span class="canvas-corner">MY NIGHT SKY</span><span class="canvas-detail">작게 보이는 배경 별은 꾸밈이에요.</span><div id="empty-board" class="empty-board"><strong>밤하늘을 톡, 눌러 보세요.</strong><span>첫 번째 별에서 나의 상상이 시작돼요.</span></div>':''}</div>`}
function demoSVG(showLines=false,hero=false){const positions=hero?[[260,240],[470,360],[790,180],[1010,430],[340,540],[800,535]]:[[180,220],[375,465],[590,290],[810,440],[1030,190]];return `<svg class="${hero?'stars-only':'observe-sky'}" viewBox="0 0 1200 700" role="img" aria-label="${hero?'자유롭게 흩어진 별':'카시오페이아자리의 다섯 별'}">${background(hero?'welcome':'demo')}${showLines?`<polyline class="demo-line" points="${positions.map(p=>p.join(',')).join(' ')}"/>`:''}${positions.map((p,i)=>`<g transform="translate(${p.join(' ')})">${starGraphic({size:i%2+1,brightness:2},hero?'welcome':'demo')}</g>`).join('')}</svg>`}
function intro(){return `<div class="hero"><div><div class="pill">별과 별 사이, 나의 상상</div><h1>나만의<br><span>별자리 만들기</span></h1><p>별과 별을 이어 보세요.<br>무엇이 떠오르나요?</p><div class="callout">우리는 북쪽 밤하늘의 별자리를 관찰했어요.<br>이번에는 별을 직접 놓고 이어<br><strong>내가 상상한 모습</strong>을 만들어 볼까요?</div><div class="button-row">${button('start','별자리 만들기 시작 →','primary')}${state.maxStep>0?button('resume','내 작품 이어 만들기','secondary'):''}</div><p class="status-line">약 10~15분 · 로그인 없이 바로 만들어요</p></div><div class="hero-card">${demoSVG(false,true)}<h2>밤하늘에는 하나의 답만 있지 않아요.</h2><p>별 배치 → 별 연결 → 모양 상상 → 이름과 이야기<br>여러분의 생각을 작품으로 남겨 보세요.</p></div></div><div class="callout intro-note">옛날 사람들은 밤하늘의 별들을 이어 사람, 동물, 물건 등의 모습을 상상했어요. 우리가 알고 있는 별자리에는 오랜 시간 사용되어 온 정해진 이름이 있어요. 이번에는 실제 별자리를 새로 정하는 것이 아니라, <strong>내가 상상한 나만의 별자리</strong>를 만들어 봐요.</div>`}
function observe(){return heading(1,'별들은 어떻게 별자리가 되었을까요?','점으로 보이는 별들을 먼저 천천히 살펴보세요.')+`<div class="observe-grid"><div>${demoSVG(ui.showDemo)}<p class="small muted" style="margin-top:12px">카시오페이아자리의 모양을 단순하게 나타냈어요. 실제 크기·위치 비율과 달라요.</p></div><div class="panel"><div class="eyebrow">짧은 관찰</div><h2>다섯 개의 별,<br>어떤 모양이 보이나요?</h2>${button('demo-toggle',ui.showDemo?'연결선 숨기기':'별을 이어 보기','primary wide')}<div class="callout" style="margin-top:22px">${state.observed?'별과 별을 연결하니 어떤 모양이 보이나요? 같은 별을 보더라도 사람마다 다른 모습을 상상할 수 있어요.':'별의 위치를 보고 떠오르는 모습을 생각해 보세요.'}</div>${state.observed?'<p class="small">옛날 사람들도 별을 보며 여러 사람, 동물, 물건의 모습을 상상했답니다.</p>':''}</div></div>`+nav('next','나만의 별자리 만들기','선을 한 번 이어 보고 나만의 밤하늘로 가요.',state.observed)}
function editor(){return `<div class="editor-top"><div><div class="eyebrow">STEP ${String(state.step).padStart(2,'0')}</div><h1>${state.step===2?'밤하늘에 별을 놓아 봐요.':'별과 별을 이어 보세요.'}</h1><p>${state.step===2?'빈 곳을 눌러 별을 놓고, 별을 선택해 색깔도 골라 보세요.':'첫 별과 다음 별을 차례로 눌러요. 네 개 이상의 별을 하나로 이어 보세요.'}</p></div><div class="counts"><span id="star-count"></span><span id="line-count"></span></div></div>${board()}<div class="tools" role="toolbar" aria-label="별자리 제작 도구">${[['add','✦ 별 놓기'],['move','↗ 선택·이동'],['connect','⌁ 별 잇기'],['draw','✎ 스케치'],['erase','스케치 지우개']].map(([t,l])=>button('tool',l,'secondary',`data-tool="${t}" aria-pressed="${ui.tool===t}"`)).join('')}<span class="tool-divider"></span>${button('delete','선택 지우기','secondary','disabled')}${button('undo','↶ 실행 취소','secondary')}${button('redo','↷ 다시 실행','secondary')}</div><div class="tool-state"><div><strong id="tool-title"></strong><span id="tool-hint"></span></div><div>${button('end-chain','이어가기 끝','quiet','id="end-chain" hidden')}${button('center-star','가운데 별 추가','quiet','id="center-star"')}</div></div><div id="selection-controls" class="selection-controls" hidden></div><section id="imagination-nudge" class="panel imagine-panel" hidden><label class="field"><span>어떤 모습이 보이나요?</span><input type="text" data-meta="appearance" maxlength="80" value="${esc(state.meta.appearance)}" placeholder="떠오른 모습을 간단히 적어도 좋아요."></label>${button('hint','상상 힌트','secondary')}<div id="hint-box" class="hint-box"></div></section>`+nav('next',state.step===2?'별 연결하기':'모양 상상하기',state.step===2?'별은 5~12개를 권해요. 최대 15개까지 놓을 수 있어요.':'별 4개 이상이 하나로 이어지면 다음으로 갈 수 있어요.',false)}
function imagine(){return heading(4,'어떤 모습이 떠오르나요?','내가 놓은 별과 선을 천천히 바라보며 상상해 보세요.')+board(false,'preview-shell')+`<section class="panel imagine-panel"><label class="field"><span>별을 이어 보니 무엇처럼 보이나요?</span><input type="text" data-meta="appearance" maxlength="80" value="${esc(state.meta.appearance)}" placeholder="떠오른 모습 한 가지를 적어 주세요."><small>이 생각이 나의 별자리 이름과 설명이 돼요.</small></label>${button('hint','상상 힌트','secondary')}<div id="hint-box" class="hint-box"></div></section>`+nav('next','이름과 이야기 만들기','다른 모양을 더해 보고 싶으면 이전으로 돌아갈 수 있어요.',!!state.meta.appearance.trim())}
function write(){return heading(5,'별자리 이름과 이야기를 만들어요.','어떤 모습을 상상했는지 글로 남겨 보세요.')+`<div class="form-grid"><div>${board(false,'preview-shell')}<div class="sentence-preview section-space" id="sentence-preview"></div></div><section class="panel"><label class="field"><span>나의 별자리 이름</span><input id="name-input" data-meta="name" type="text" maxlength="24" value="${esc(state.meta.name)}" placeholder="내가 직접 정하는 이름"><small>이름 뒤에 ‘자리’가 자동으로 붙지 않아요.</small></label><label class="field"><span>별을 이어 보니…</span><input data-meta="appearance" type="text" maxlength="80" value="${esc(state.meta.appearance)}" placeholder="떠오른 모습"><small>…처럼 보여서 이렇게 이름을 지었습니다.</small></label><label class="field"><span>이 별자리의 이야기 <span class="optional">선택</span></span><textarea data-meta="story" maxlength="240" rows="4" placeholder="더 들려주고 싶은 이야기가 있으면 2~4줄로 적어요.">${esc(state.meta.story)}</textarea><small>이야기는 비워 두어도 완성할 수 있어요.</small></label><label class="field"><span>만든 사람</span><input data-meta="author" type="text" maxlength="16" value="${esc(state.meta.author)}" placeholder="이름 또는 번호"><small>번호만 적어도 좋아요.</small></label><div id="form-error" class="validation-message" role="alert" hidden></div></section></div>`+nav('finish','작품 완성하기','이름, 떠오른 모습, 만든 사람을 적어 주세요.')}
function completed(){return `<section class="artwork ${ui.freshFinish?'fresh':''}"><div class="work-header"><div><p class="complete-message">✧ 나만의 별자리가 완성되었습니다!</p><div class="eyebrow">나의 창작 별자리</div><h1>${esc(state.meta.name)}</h1></div><div class="author">${esc(state.meta.author)}의 별자리</div></div>${board(false)}<div class="work-description"><h2>이렇게 만들었어요</h2><p>${esc(E.description(state.meta))}</p>${state.meta.story.trim()?`<p class="story">${esc(state.meta.story.trim())}</p>`:''}</div><p class="creation-note">${E.NOTICE}</p><div class="work-actions">${button('export','내 별자리 이미지 저장','primary')}</div><p class="small muted">완성한 별자리를 이미지로 저장해 보세요.</p><div id="export-result"></div></section>`}
function render(scroll=false){$('#steps').innerHTML=steps.map((label,i)=>{const step=i+1;return button('jump',`<span class="step-num">${step<state.maxStep?'✓':step}</span><span>${label}</span>`,step===state.step?'current':step<state.maxStep?'visited':'',`data-step="${step}" ${step>state.maxStep?'disabled':''} ${step===state.step?'aria-current="step"':''}`)}).join('');$('#main').innerHTML=`<div class="page">${[intro,observe,editor,editor,imagine,write,completed][state.step]()}</div>`;paintBoard();updateEditor();updateSentence();if(scroll){window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true})}save()}
function touchRadius(){const svg=$('#sky-board');let scale=svg?.getScreenCTM?.()?.a;if(!Number.isFinite(scale)||scale<=0)scale=1;return Math.max(25,26/scale)}
function paintBoard(){const svg=$('#sky-board');if(!svg)return;svg.innerHTML=svgContent(state.drawing,'work',state.step===2||state.step===3);const empty=$('#empty-board');if(empty)empty.hidden=state.drawing.stars.length>0}
function updateSentence(){const el=$('#sentence-preview');if(el)el.innerHTML=`내가 만든 별자리의 이름은 <strong>${esc(state.meta.name||'______')}</strong>입니다.<br>별을 이어 보니 <strong>${esc(state.meta.appearance||'______')}</strong>처럼 보여서 이렇게 이름을 지었습니다.`}
function updateEditor(){const editing=state.step===2||state.step===3;if(!editing)return;const star=state.drawing.stars.find(s=>s.id===ui.selected);if(!star)ui.selected=null;if(!state.drawing.lines.some(l=>l.id===ui.line))ui.line=null;const modes={add:['지금은 별 놓기 중이에요.','빈 밤하늘을 누르거나, 놓은 별을 끌어 보세요.'],move:['지금은 선택·이동 중이에요.','별을 끌어 움직이거나 연결선을 눌러 선택해요.'],connect:['지금은 별 연결하기 중이에요.',ui.anchor?'이제 연결할 다음 별을 선택하세요.':'연결할 첫 번째 별을 선택하세요.'],draw:['지금은 상상 그림 그리기 중이에요.','선택 활동이에요. 손가락이나 마우스로 얇게 그려요.'],erase:['지금은 스케치 지우개예요.','내가 그린 스케치 선을 누르면 한 획씩 지워져요.']};$('#tool-title').textContent=modes[ui.tool][0];$('#tool-hint').textContent=modes[ui.tool][1];$('#star-count').textContent=`별 ${state.drawing.stars.length} / 15`;$('#line-count').textContent=`연결 ${state.drawing.lines.length}개`;document.querySelectorAll('[data-action="tool"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===ui.tool)));$('[data-action="undo"]').disabled=undo.length===0;$('[data-action="redo"]').disabled=redo.length===0;$('[data-action="delete"]').disabled=!ui.selected&&!ui.line;$('#end-chain').hidden=!ui.anchor||ui.tool!=='connect';$('#center-star').hidden=ui.tool!=='add';const controls=$('#selection-controls');controls.hidden=!star;if(star)controls.innerHTML=`<div class="segmented"><span>선택한 별 크기</span>${['작게','중간','크게'].map((l,i)=>button('size',l,'secondary',`data-value="${i}" aria-pressed="${star.size===i}"`)).join('')}</div><div class="segmented"><span>밝기</span>${['은은하게','보통','밝게'].map((l,i)=>button('brightness',l,'secondary',`data-value="${i}" aria-pressed="${star.brightness===i}"`)).join('')}</div><div class="segmented star-colors" role="group" aria-label="선택한 별 색깔"><span>선택한 별 색깔</span>${C.STAR_COLORS.map(c=>button('color',`<span class="color-dot" style="--star-color:${c.hex}" aria-hidden="true"></span>${c.label}`,'secondary',`data-value="${c.id}" aria-pressed="${C.starColor(star).id===c.id}"`)).join('')}</div><p class="size-help">화면에서 보이는 별의 색깔·크기·밝기는 별자리를 꾸미기 위한 표현이에요.</p>`;const ready=C.largestGroup(state.drawing)>=4;$('#imagination-nudge').hidden=!ready;$('[data-action="next"]').disabled=state.step===2?state.drawing.stars.length<2:!ready}
function chooseTool(tool){if(tool==='connect'&&state.drawing.stars.length<2){notify(state.drawing.stars.length?'별을 하나 더 만들어야 연결할 수 있어요.':'먼저 별을 2개 이상 만들어 주세요.');return}ui.tool=tool;ui.anchor=null;ui.line=null;paintBoard();updateEditor()}
function addAt(p){if(state.drawing.stars.length>=C.MAX_STARS){notify('별이 너무 많으면 모양을 찾기 어려울 수 있어요. 지금 있는 15개의 별을 이용해 볼까요?');return}changeDrawing(()=>{ui.selected=C.addStar(state.drawing,p.x,p.y);ui.line=null});if(state.drawing.stars.length===13)notify('별은 5~12개를 권해요. 지금 있는 별에서 모양을 찾아볼까요?')}
function linkStar(id){ui.selected=id;ui.line=null;if(!ui.anchor){ui.anchor=id;notify('이제 연결할 두 번째 별을 선택하세요.')}else{const from=ui.anchor;let result;changeDrawing(()=>result=C.connect(state.drawing,from,id));if(result==='same'){ui.anchor=null;notify('이어가기를 끝냈어요. 다른 별에서 다시 시작할 수 있어요.')}else{ui.anchor=id;if(result==='duplicate')notify('이미 이어진 선이에요. 다음 별을 선택해 보세요.')}}paintBoard();updateEditor()}
function deleteSelected(){if(ui.selected){const id=ui.selected;changeDrawing(()=>C.removeStar(state.drawing,id));ui.anchor=null;ui.selected=null;notify('별과 이어진 선을 함께 지웠어요.')}else if(ui.line){const id=ui.line;changeDrawing(()=>state.drawing.lines=state.drawing.lines.filter(l=>l.id!==id));ui.line=null;notify('선택한 연결을 지웠어요.')}paintBoard();updateEditor()}
function localPoint(event){const svg=$('#sky-board'),matrix=svg?.getScreenCTM?.();if(!matrix)return null;try{const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const p=point.matrixTransform(matrix.inverse());return {x:p.x/1200,y:p.y/700}}catch{return null}}
function pointerDown(e){if(!(state.step===2||state.step===3)||gesture||e.isPrimary===false||e.button>0)return;const svg=e.target.closest('#sky-board');if(!svg)return;const p=localPoint(e);if(!p||p.x<0||p.x>1||p.y<0||p.y>1)return;e.preventDefault();const before=C.copy(state.drawing);if(ui.tool==='draw'){if(state.drawing.strokes.length>=C.MAX_STROKES){notify('스케치가 많아요. 지우개로 조금 지우고 그려 보세요.');return}pendingStroke={id:'p'+state.drawing.nextId,points:[C.point(p.x,p.y)]};gesture={type:'draw',pointer:e.pointerId,before,svg};svg.setPointerCapture?.(e.pointerId);return}if(ui.tool==='erase'){gesture={type:'erase',pointer:e.pointerId,before,svg};C.eraseStroke(state.drawing,p,touchRadius());svg.setPointerCapture?.(e.pointerId);paintBoard();return}const star=C.nearestStar(state.drawing,p,touchRadius());if(star){if(ui.tool==='connect'){linkStar(star.id);return}ui.selected=star.id;ui.line=null;ui.anchor=null;gesture={type:'move',id:star.id,pointer:e.pointerId,before,svg,offset:{x:star.x-p.x,y:star.y-p.y}};svg.setPointerCapture?.(e.pointerId);paintBoard();updateEditor();return}const line=e.target.closest('[data-line]');if(line){ui.line=line.dataset.line;ui.selected=ui.anchor=null;paintBoard();updateEditor();return}if(ui.tool==='add')addAt(p);else{ui.selected=ui.line=null;if(ui.tool==='connect')ui.anchor=null;paintBoard();updateEditor()}}
function pointerMove(e){if(!gesture||e.pointerId!==gesture.pointer)return;const p=localPoint(e);if(!p)return;e.preventDefault();if(gesture.type==='move')C.moveStar(state.drawing,gesture.id,p.x+gesture.offset.x,p.y+gesture.offset.y);else if(gesture.type==='draw'){const last=pendingStroke.points.at(-1);if(pendingStroke.points.length<180&&Math.hypot((p.x-last.x)*1200,(p.y-last.y)*700)>4)pendingStroke.points.push(C.point(p.x,p.y))}else C.eraseStroke(state.drawing,p,touchRadius());paintBoard()}
function endGesture(e,cancel=false){if(!gesture||e&&e.pointerId!==gesture.pointer)return;const g=gesture;gesture=null;if(cancel){state.drawing=g.before;pendingStroke=null}else{if(g.type==='draw'&&pendingStroke?.points.length>1){state.drawing.strokes.push(pendingStroke);state.drawing.nextId++}pendingStroke=null;commit(g.before)}try{if(g.svg.hasPointerCapture?.(g.pointer))g.svg.releasePointerCapture(g.pointer)}catch{}paintBoard();updateEditor();save()}
function finish(){const error=C.largestGroup(state.drawing)<4?'별 4개 이상을 하나로 이어 주세요.':!state.meta.name.trim()?'나만의 별자리 이름을 지어 주세요.':!state.meta.appearance.trim()?'무엇처럼 보이는지 적어 주세요.':!state.meta.author.trim()?'만든 사람의 이름 또는 번호를 적어 주세요.':'';if(error){const el=$('#form-error');if(el){el.textContent=error;el.hidden=false}notify(error);return}for(const k of Object.keys(state.meta))state.meta[k]=state.meta[k].trim();state.step=6;state.maxStep=6;state.completed=true;ui.freshFinish=true;save();render(true);ui.freshFinish=false}
async function exportPNG(){const b=$('[data-action="export"]');if(b)b.disabled=true;try{if(document.fonts){await document.fonts.load('24px "NightSkyKorean"');await document.fonts.ready;}const canvas=document.createElement('canvas');E.render(canvas,state.drawing,state.meta);const url=canvas.toDataURL('image/png');if(!url.startsWith('data:image/png'))throw Error('PNG generation failed');const name=('나의별자리_'+state.meta.name).replace(/[\\/:*?"<>|]/g,'_').slice(0,60)+'.png';const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();const el=$('#export-result');if(el){el.innerHTML='<details class="png-fallback"><summary>저장이 안 되면 완성 이미지를 여기서 열어 보세요.</summary><p class="small">이미지를 길게 눌러 저장하거나 아래 링크를 눌러 주세요.</p></details>';const image=document.createElement('img');image.src=url;image.alt='저장용 완성 별자리 이미지';const link=document.createElement('a');link.href=url;link.download=name;link.textContent='PNG 다시 저장';el.firstElementChild.append(image,link)}notify('1600 × 1000 PNG를 만들었어요. 기기의 다운로드 항목을 확인해 보세요.')}catch{notify('이미지 저장을 완료하지 못했어요. Chrome에서 다시 시도해 주세요.')}finally{if(b)b.disabled=false}}
function hint(){let next=Math.floor(Math.random()*hints.length);if(next===ui.hint)next=(next+1)%hints.length;ui.hint=next;const box=$('#hint-box');if(box)box.textContent=hints[next]}
const actions={start:()=>go(1),resume:()=>{const target=state.completed?6:Math.max(1,state.maxStep);if(target===6)finish();else go(target)},back:()=>go(Math.max(0,state.step-1)),next:()=>go(state.step+1),jump:b=>{const n=Number(b.dataset.step);if(n<=state.maxStep)go(n)},'demo-toggle':()=>{ui.showDemo=!ui.showDemo;state.observed=true;save();render(false)},tool:b=>chooseTool(b.dataset.tool),'center-star':()=>addAt({x:.5,y:.5}),'end-chain':()=>{ui.anchor=null;paintBoard();updateEditor()},delete:deleteSelected,undo:undoAction,redo:redoAction,size:b=>{const star=state.drawing.stars.find(s=>s.id===ui.selected);if(star)changeDrawing(()=>star.size=Number(b.dataset.value))},brightness:b=>{const star=state.drawing.stars.find(s=>s.id===ui.selected);if(star)changeDrawing(()=>star.brightness=Number(b.dataset.value))},color:b=>{const star=state.drawing.stars.find(s=>s.id===ui.selected);if(star&&C.STAR_COLORS.some(c=>c.id===b.dataset.value))changeDrawing(()=>star.color=b.dataset.value)},hint,finish,export:exportPNG};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)actions[b.dataset.action]?.(b)});
document.addEventListener('input',e=>{const key=e.target.dataset.meta;if(!Object.hasOwn(state.meta,key))return;const limit={name:24,appearance:80,story:240,author:16}[key];state.meta[key]=e.target.value.slice(0,limit);state.completed=false;save();updateSentence();if(state.step===4)$('[data-action="next"]').disabled=!state.meta.appearance.trim()});
document.addEventListener('pointerdown',pointerDown);document.addEventListener('pointermove',pointerMove,{passive:false});document.addEventListener('pointerup',e=>endGesture(e));document.addEventListener('pointercancel',e=>endGesture(e,true));window.addEventListener('blur',()=>endGesture(null,true));
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&(state.step===2||state.step===3)){e.preventDefault();e.shiftKey?redoAction():undoAction();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'&&(state.step===2||state.step===3)){e.preventDefault();redoAction();return}if(e.key==='Escape'){ui.anchor=null;paintBoard();updateEditor();return}if(!(state.step===2||state.step===3))return;const node=e.target.closest('[data-star]');const line=e.target.closest('[data-line]');if(node){const id=node.dataset.star;if(e.key==='Enter'||e.key===' '){e.preventDefault();if(ui.tool==='connect')linkStar(id);else{ui.selected=id;ui.line=null;paintBoard();updateEditor()}}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const s=state.drawing.stars.find(s=>s.id===id),delta=e.shiftKey?.004:.015;if(s){ui.selected=id;changeDrawing(()=>C.moveStar(state.drawing,id,s.x+(e.key==='ArrowLeft'?-delta:e.key==='ArrowRight'?delta:0),s.y+(e.key==='ArrowUp'?-delta:e.key==='ArrowDown'?delta:0)))}}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();ui.selected=id;deleteSelected()}$(`[data-star="${id}"]`)?.focus()}else if(line&&(e.key==='Enter'||e.key===' '||e.key==='Delete'||e.key==='Backspace')){e.preventDefault();ui.line=line.dataset.line;ui.selected=null;if(e.key==='Delete'||e.key==='Backspace')deleteSelected();else{paintBoard();updateEditor();$(`[data-line="${ui.line}"]`)?.focus()}}});
$('#home').addEventListener('click',e=>{e.preventDefault();go(0)});$('#reset-open').addEventListener('click',()=>$('#reset-dialog').showModal());$('#reset-cancel').addEventListener('click',()=>$('#reset-dialog').close());$('#reset-confirm').addEventListener('click',()=>{state=fresh();undo=[];redo=[];gesture=null;pendingStroke=null;ui.tool='add';ui.selected=ui.line=ui.anchor=null;ui.showDemo=false;$('#reset-dialog').close();save();render(true);notify('새로운 밤하늘을 준비했어요.')});$('#help-open').addEventListener('click',()=>$('#help-dialog').showModal());$('#help-close').addEventListener('click',()=>$('#help-dialog').close());
window.addEventListener('resize',()=>paintBoard());
render(false);
})();
