(function(root){
'use strict';
const C=typeof module==='object'&&module.exports?require('./model.js'):root.ConstellationCore;
const FONT='"NightSkyKorean", "Malgun Gothic", "Apple SD Gothic Neo", "Noto Sans CJK KR", "Noto Sans KR", sans-serif';
const NOTICE='이 별자리는 실제 별자리가 아니라 밤하늘의 별을 보고 상상하여 만든 창작 별자리입니다.';
function wrap(ctx,text,maxWidth){const lines=[];for(const paragraph of String(text).split('\n')){let line='';for(const ch of paragraph){if(line&&ctx.measureText(line+ch).width>maxWidth){lines.push(line);line=ch}else line+=ch}lines.push(line)}return lines}
function description(meta){return `내가 만든 별자리의 이름은 “${meta.name}”입니다.\n별을 이어 보니 “${meta.appearance}”처럼 보여서 이렇게 이름을 지었습니다.`}
function paintSky(ctx,w,h){const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'#0c1833');bg.addColorStop(.55,'#111d38');bg.addColorStop(1,'#071126');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w*.57,h*.44);ctx.rotate(-.4);ctx.scale(1,.22);const mist=ctx.createRadialGradient(0,0,0,0,0,w*.75);mist.addColorStop(0,'rgba(130,155,195,.12)');mist.addColorStop(.45,'rgba(83,109,156,.055)');mist.addColorStop(1,'rgba(83,109,156,0)');ctx.fillStyle=mist;ctx.fillRect(-w,-h*4,w*2,h*8);ctx.restore();for(const b of C.backgroundStars()){ctx.beginPath();ctx.fillStyle=`rgba(220,230,250,${b.opacity})`;ctx.arc(b.x*w,b.y*h,b.r,0,Math.PI*2);ctx.fill()}}
function paintDrawing(ctx,d,box,{lines=true,sketch=true}={}){const scale=Math.min(box.w/C.WIDTH,box.h/C.HEIGHT),ox=box.x+(box.w-C.WIDTH*scale)/2,oy=box.y+(box.h-C.HEIGHT*scale)/2;ctx.save();ctx.translate(ox,oy);ctx.scale(scale,scale);const lookup=new Map(d.stars.map(s=>[s.id,s]));if(sketch){ctx.strokeStyle='rgba(238,209,153,.64)';ctx.lineWidth=2.6;ctx.lineCap='round';ctx.lineJoin='round';for(const st of d.strokes){ctx.beginPath();st.points.forEach((p,i)=>i?ctx.lineTo(p.x*C.WIDTH,p.y*C.HEIGHT):ctx.moveTo(p.x*C.WIDTH,p.y*C.HEIGHT));ctx.stroke()}}if(lines){ctx.strokeStyle='rgba(154,206,241,.78)';ctx.lineWidth=2.2;ctx.lineCap='round';for(const l of d.lines){const a=lookup.get(l.a),b=lookup.get(l.b);if(!a||!b)continue;ctx.beginPath();ctx.moveTo(a.x*C.WIDTH,a.y*C.HEIGHT);ctx.lineTo(b.x*C.WIDTH,b.y*C.HEIGHT);ctx.stroke()}}for(const s of d.stars){const x=s.x*C.WIDTH,y=s.y*C.HEIGHT,r=[3.5,5,7][s.size];ctx.save();ctx.globalAlpha=[.65,.85,1][s.brightness];ctx.shadowColor='#e0e9ff';ctx.shadowBlur=[8,13,18][s.brightness];ctx.fillStyle=s.size===2?'#fff4d9':'#f4f7ff';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(227,239,255,.13)';ctx.beginPath();ctx.arc(x,y,r*2.2,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore()}
function render(canvas,d,meta){canvas.width=1600;canvas.height=1000;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Canvas not supported');paintSky(ctx,1600,1000);ctx.textBaseline='alphabetic';ctx.textAlign='left';ctx.fillStyle='#b9c9e2';ctx.font=`20px ${FONT}`;ctx.fillText('밤하늘 상상 연구소 · 나만의 창작 별자리',70,46);ctx.fillStyle='#f4f6ff';let titleSize=46;do{ctx.font=`600 ${titleSize}px ${FONT}`;if(ctx.measureText(meta.name).width<=1450)break;titleSize-=2}while(titleSize>24);ctx.fillText(meta.name,70,104);ctx.font=`23px ${FONT}`;ctx.fillStyle='#c7d7ed';ctx.textAlign='right';ctx.fillText(`만든 사람: ${meta.author}`,1530,144);ctx.textAlign='left';ctx.font=`24px ${FONT}`;let text=description(meta)+(meta.story.trim()?'\n\n'+meta.story.trim().replace(/\s+/g,' '):'');const textLines=wrap(ctx,text,1460);const lineHeight=31;const textHeight=textLines.length*lineHeight;const artTop=156,artBottom=920-textHeight-30;paintDrawing(ctx,d,{x:70,y:artTop,w:1460,h:Math.max(365,artBottom-artTop)});const textTop=artBottom+32;ctx.strokeStyle='rgba(176,198,225,.23)';ctx.beginPath();ctx.moveTo(70,artBottom+6);ctx.lineTo(1530,artBottom+6);ctx.stroke();ctx.fillStyle='#e1e9f7';ctx.font=`24px ${FONT}`;textLines.forEach((line,i)=>ctx.fillText(line,70,textTop+i*lineHeight));ctx.fillStyle='#a5b6d2';ctx.font=`18px ${FONT}`;wrap(ctx,NOTICE,1460).forEach((line,i)=>ctx.fillText(line,70,970+i*22));return canvas}
const API={render,paintDrawing,paintSky,description,wrap,NOTICE};if(typeof module==='object'&&module.exports)module.exports=API;else root.ConstellationExport=API;
})(typeof window!=='undefined'?window:globalThis);
